services:
  app:
    image: thekeele/keele.codes:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # local
      - ./nginx-certbot.conf:/etc/nginx/nginx-certbot.conf # certificate generation
    depends_on:
      - app
    restart: unless-stopped
