services:
  app:
    image: thekeele/keele.codes:latest
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot-web:/usr/share/nginx/html   # For Let's Encrypt challenges
      - certbot-certs:/etc/letsencrypt      # Store certificates
    depends_on:
      - app
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-web:/var/www/html          # Shared with Nginx for challenges
      - certbot-certs:/etc/letsencrypt     # Store certificates
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      - CERTBOT_EMAIL=mark@keele.codes
    depends_on:
      - nginx
    restart: always

volumes:
  certbot-web:      # Define the certbot-web volume
  certbot-certs:    # Define the certbot-certs volume
