services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-staging.conf:/etc/nginx/nginx.conf # local
      - ./nginx-certbot.conf:/etc/nginx/nginx-certbot.conf # certificate generation
      - /home/mark/resume:/home/mark/resume:ro
      - /home/mark/bitcoin:/home/mark/bitcoin:ro
    depends_on:
      - app
    restart: unless-stopped
