name: Deploy keele.codes

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull Latest
      uses: appleboy/ssh-action@v0.1.5
      with:
        debug: true
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASS }}
        script: |
          cd keele.codes/
