name: keele.codes CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'

    name: Deploy Release
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Release to keele.codes
      uses: appleboy/ssh-action@v0.1.4
      with:
        script_stop: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd keele.codes/
          git pull origin master
