name: Keele Codes CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Deploy release to keele.codes
      uses: appleboy/ssh-action@v0.1.3
      with:
        script_stop: true
        debug: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          ls
          cd keele.codes/
          git pull origin master
